#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 19 21:23:08 2019

@author: mlavoie
"""
##################################################################################################
# This is a python 3 script with two functions (testToSpeech and play)
# The first function "textToSpeech" convert text to a recorded .mp3 file
# The second function "play" allow playing the .mp3 file generated by the first function
###################################################################################################

from gtts import gTTS

import os

def textToSpeech(text, language="en", slow=False):
    myObj = gTTS(text=text, lang=language, slow=False)
    
    return(myObj.save("text.mp3"))
    
    #return(os.system("mpg321 text.mp3"))

def play(tune):
  tune = "mpg321 " + tune
  return(os.system(tune))
#####################################################################################################


##################################################################################################
# Details about importing the python packages as well as mpg321

# Install gtts package using pip install gtts

# Install mpg321, a free command line mp3 player
# To do so, on MAC, Press Command+Space and type Terminal and press enter/return key.
# Run in the Terminal :
# ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
# and press enter/return key.
# If the screen prompts you to enter a password, please enter your Mac's user password to continue. When you type the password, it won't be displayed on screen, but the system would accept it. So just type your password and press ENTER/RETURN key. Then wait for the command to finish.
# Run:
# brew install mpg321
# Done! You can now use mpg321.
###############################################################################################

################################################################################################
# # Example of a function and of the use of gtts
# ##############################################################################################

# from gtts import gTTS
# 
# import os
# 
# text = "Welcome to this game"
# 
# language = "en"
# 
# myObj = gTTS(text=text, lang=language, slow=False)
# 
# myObj.save("welcome.mp3")
# 
# os.system("mpg321 welcome.mp3")
# ##########################################################################################
